In [15]:
import numpy as np
import copy as cp

# empty cells are represented by 0
board =[[0, 2, 0, 7, 0, 0, 0, 1, 5],
       [0, 0, 0, 0, 0, 0, 6, 0, 0],
       [5, 0, 0, 9, 0, 0, 0, 0, 0],
       [8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0],
       [0, 0, 6, 0, 0, 4, 0, 7, 3],
       [0, 0, 7, 8, 0, 1, 0, 6, 0],
       [0, 0, 4, 0, 7, 0, 0, 5, 0],
       [0, 0, 3, 0, 4, 9, 0, 0, 0]]

board = np.array(board)
unsolved_board = cp.deepcopy(board)

In [16]:
def in_row(number, row): 
    return number in board[row]

# returns true if number (integer between 1 and 9) is in the row row
# (an integer between 0 and 8) and else false

True

In [18]:
def in_column(number, column):
    return number in board[:,column]

# returns true if number (integer between 1 and 9) is in the column column
# (an integer between 0 and 8) and else false

False

In [19]:
def in_square(number, sqr):
    insqr = False
    for l in board[sqr[0]*3:(sqr[0]+1)*3,sqr[1]*3:(sqr[1]+1)*3]:
        if number in l:
            insqr = True
    return insqr

# returns true if number (integer between 1 and 9) is in le square sqr
# (sqr is a cell (3x3) defined be a tuple (i,j) with i and j integers between 0 and 2)
# for example in_square(1, (0,2)) returns true if 2 is in the square (0,0) (the one in the board's upper left), else false

True

In [20]:
def check(number, row, column):
    return (not in_row(number, row) 
            and not in_column(number, column) 
            and not in_square(number, (row//3, column//3)))

# checks if number (integer between 1 and 9) can be in the cell (row, column)
# (row and column are integers between 0 and 8)

In [21]:
def find_empty(board):
    for i in range(len(board)):
        for j in range(len(board[0])):
            if board[i][j] == 0:
                return (i, j)
    return None

# returns a tuple (i,j) of an empty cell (i and j are integers between 0 and 8)

In [22]:
def solve(board): 
    empty = find_empty(board)
    if not empty:   
        return True
    else:
        row = empty[0]
        column = empty[1]
    for i in range(1,10):
        if check (i , row, column):
            board[row][column] = i
            if solve(board):
                return True
            else:
                board[row][column] = 0        
    return False

In [23]:
print("Unsolved board")
print(unsolved_board,"\n")

print("Solved board")
print(board)

Unsolved board
[[0 2 0 7 0 0 0 1 5]
 [0 0 0 0 0 0 6 0 0]
 [5 0 0 9 0 0 0 0 0]
 [8 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2 0]
 [0 0 6 0 0 4 0 7 3]
 [0 0 7 8 0 1 0 6 0]
 [0 0 4 0 7 0 0 5 0]
 [0 0 3 0 4 9 0 0 0]] 

True
Solved board
[[4 2 9 7 6 3 8 1 5]
 [3 7 8 4 1 5 6 9 2]
 [5 6 1 9 2 8 7 3 4]
 [8 3 2 1 5 7 9 4 6]
 [7 4 5 3 9 6 1 2 8]
 [1 9 6 2 8 4 5 7 3]
 [2 5 7 8 3 1 4 6 9]
 [9 8 4 6 7 2 3 5 1]
 [6 1 3 5 4 9 2 8 7]]
